In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import jaccard_score
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

In [2]:
id_information = pd.read_csv('id_information_mmsr.tsv', sep='\t')
id_genres = pd.read_csv('id_genres_mmsr.tsv', sep='\t')
id_bert = pd.read_csv('id_bert_mmsr.tsv', sep='\t')
id_lyrics_tfidf = pd.read_csv('id_lyrics_tf-idf_mmsr.tsv', sep='\t')
id_lyrics_word2vec = pd.read_csv('id_lyrics_word2vec_mmsr.tsv', sep='\t')

In [17]:
query_id = 'h48f46ZsT9h0Z5Dm'

In [4]:
#function that returns conine similarity between a rowvector(1,c) and a matrix of rowvectors (r,c)
#returns columnvector (r,1)

def cosine_similarities(x, Y):
    nx = np.linalg.norm(x)
    nY = np.linalg.norm(Y, axis=1, keepdims=True)
    DotP = np.dot(x, Y.T).T
    
    return DotP/((nx*nY)+1e-10)

In [18]:
tfidf_subset = id_lyrics_tfidf
tfidf_query = id_lyrics_tfidf.loc[id_lyrics_tfidf['id']==query_id]
tfidf_query = np.array(tfidf_query.drop(columns=['id']))
subset_ids = tfidf_subset[['id']].copy()

tfidf_no_id = np.array(tfidf_subset.drop(columns=['id']))
cosine = cosine_similarities(tfidf_query, tfidf_no_id)
subset_ids.insert(1,'cosine_ifidf', cosine)


bert_subset = id_bert
bert_query = id_bert.loc[id_bert['id']==query_id]
bert_query = np.array(bert_query.drop(columns=['id']))

bert_no_id = np.array(bert_subset.drop(columns=['id']))
cosine = cosine_similarities(bert_query, bert_no_id)
subset_ids.insert(1,'cosine_bert', cosine)


word2vec_subset = id_lyrics_word2vec
word2vec_query = id_lyrics_word2vec.loc[id_lyrics_word2vec['id']==query_id]
word2vec_query = np.array(word2vec_query.drop(columns=['id']))

word2vec_no_id = np.array(word2vec_subset.drop(columns=['id']))
cosine = cosine_similarities(word2vec_query, word2vec_no_id)
subset_ids.insert(1,'cosine_word2vec', cosine)
subset_ids_without_id = subset_ids.drop(columns=['id'])

avg_cosin = subset_ids_without_id.mean(axis=1)
subset_ids.insert(1, 'avg_cosin', avg_cosin)
subset_ids

                     id  avg_cosin  cosine_word2vec  cosine_bert  cosine_ifidf
0      9jbSytob9XRzwvB6   0.531220         0.870317     0.637359      0.085985
1      Njp6JPM8vitbhVJU   0.489647         0.869094     0.575811      0.024038
2      h48f46ZsT9h0Z5Dm   0.935999         0.807997     1.000000      1.000000
3      ZmXVK43zlqdeq6z8   0.489669         0.787993     0.599210      0.081802
4      PV5EXN6AIVBqvsLO   0.412894         0.787977     0.402015      0.048689
...                 ...        ...              ...          ...           ...
76110  R4VMVAxVOAEWBjgg   0.437973         0.840102     0.460125      0.013691
76111  YgII1tHAaAnh14Kf   0.249109         0.747327     0.000000      0.000000
76112  76qenAf8gYlH4pfq   0.452445         0.793357     0.507454      0.056524
76113  9F8jQjeibAuZinEP   0.486966         0.840110     0.541384      0.079405
76114  njEze6oZPy3MX2dN   0.415861         0.789287     0.403651      0.054645

[76115 rows x 5 columns]

In [19]:
tfidf_query[tfidf_query != 0.0]=1
tfidf_no_id[tfidf_no_id != 0.0]=1
scores = []
for row in tqdm(tfidf_no_id):
    jaccard = jaccard_score(tfidf_query[0], row)
    scores.append(jaccard)
    
#AUSKOMMENTIEREN bei neustart!!!!!!
subset_ids.insert(1,'jaccard_ifidf', scores)

subset_ids

100%|███████████████████████████████████████████████████████████████████████████| 76115/76115 [03:11<00:00, 398.08it/s]

,id,jaccard_ifidf,avg_cosin,cosine_word2vec,cosine_bert,cosine_ifidf
0,9jbSytob9XRzwvB6,0.070423,0.531220,0.870317,0.637359,0.085985
1,Njp6JPM8vitbhVJU,0.032258,0.489647,0.869094,0.575811,0.024038
2,h48f46ZsT9h0Z5Dm,1.000000,0.935999,0.807997,1.000000,1.000000
3,ZmXVK43zlqdeq6z8,0.073171,0.489669,0.787993,0.599210,0.081802
4,PV5EXN6AIVBqvsLO,0.057692,0.412894,0.787977,0.402015,0.048689
...,...,...,...,...,...,...
76110,R4VMVAxVOAEWBjgg,0.052632,0.437973,0.840102,0.460125,0.013691
76111,YgII1tHAaAnh14Kf,0.000000,0.249109,0.747327,0.000000,0.000000
76112,76qenAf8gYlH4pfq,0.075949,0.452445,0.793357,0.507454,0.056524
76113,9F8jQjeibAuZinEP,0.082353,0.486966,0.840110,0.541384,0.079405
76114,njEze6oZPy3MX2dN,0.067797,0.415861,0.789287,0.403651,0.054645

In [9]:

subset_ids_new = subset_ids.drop(columns=['avg_cosin'])
subset_ids_without_id = subset_ids_new.drop(columns=['id'])
avg_sim = subset_ids_without_id.mean(axis=1)
subset_ids_new.insert(1, 'avg_similarity', avg_sim)
subset_ids_new

,id,avg_similarity,jaccard_ifidf,cosine_word2vec,cosine_bert,cosine_ifidf
0,9jbSytob9XRzwvB6,0.396055,0.129032,0.806936,0.529679,0.118572
1,Njp6JPM8vitbhVJU,0.314507,0.068966,0.750727,0.421141,0.017193
2,h48f46ZsT9h0Z5Dm,0.355791,0.090000,0.741160,0.551735,0.040268
3,ZmXVK43zlqdeq6z8,0.334533,0.093458,0.694061,0.469743,0.080871
4,PV5EXN6AIVBqvsLO,0.338576,0.120968,0.723260,0.338992,0.171086
...,...,...,...,...,...,...
76110,R4VMVAxVOAEWBjgg,0.304360,0.032000,0.765757,0.411614,0.008071
76111,YgII1tHAaAnh14Kf,0.194154,0.000000,0.776617,0.000000,0.000000
76112,76qenAf8gYlH4pfq,0.336834,0.117647,0.620901,0.520277,0.088509
76113,9F8jQjeibAuZinEP,0.322471,0.100000,0.762018,0.387903,0.039964
76114,njEze6oZPy3MX2dN,0.344671,0.095238,0.826070,0.407944,0.049434

In [20]:
subset_ids= subset_ids_new.sort_values('avg_similarity', ascending=False)
subset_ids.head(100)

,id,avg_similarity,jaccard_ifidf,cosine_word2vec,cosine_bert,cosine_ifidf
2960,00IeldeA9ijZOL0P,0.939500,1.000000,0.757998,1.000000,1.000000
4951,PWS8XcQ49VSJyvYq,0.573859,0.135417,0.768809,0.779564,0.611648
10217,8YjGB7VFMjEwZw68,0.554770,0.070423,0.790592,0.670587,0.687480
19209,waexM2D7S6PDhd9E,0.552922,0.036145,0.718893,0.732535,0.724115
11607,qufhHxuIo00xTDhF,0.550694,0.142857,0.749182,0.698532,0.612206
...,...,...,...,...,...,...
1910,DQh8SP1dAIx5aFxN,0.467866,0.019608,0.702596,0.509946,0.639316
15458,m2kwB6mpHnEWnrNH,0.467848,0.113402,0.733102,0.553835,0.471051
6337,y0kYriRUa9eDNVFM,0.467384,0.105769,0.778729,0.513227,0.471812
71740,vqxDzu71MD4QrlxV,0.467153,0.156250,0.799204,0.603685,0.309472
34756,iZnCdJ56zOz3VQuC,0.466633,0.245098,0.638176,0.757479,0.225778

In [21]:
#similarity_df = pd.DataFrame()
similarity_df.insert(0, query_id, subset_ids['id'])
similarity_df

       h48f46ZsT9h0Z5Dm  00IeldeA9ijZOL0P
2960   00IeldeA9ijZOL0P  00IeldeA9ijZOL0P
4951   PWS8XcQ49VSJyvYq  PWS8XcQ49VSJyvYq
10217  8YjGB7VFMjEwZw68  8YjGB7VFMjEwZw68
19209  waexM2D7S6PDhd9E  waexM2D7S6PDhd9E
11607  qufhHxuIo00xTDhF  qufhHxuIo00xTDhF
...                 ...               ...
10508  CkATShcOg2IfPjfl  CkATShcOg2IfPjfl
59694  rq1gAMyxp0pIX5Jg  rq1gAMyxp0pIX5Jg
21957  QDHyM3dEGPklSb7X  QDHyM3dEGPklSb7X
40747  EcA1vOBILLRLsfjd  EcA1vOBILLRLsfjd
34103  Pijn2qevwuEPUj9j  Pijn2qevwuEPUj9j

[76115 rows x 2 columns]